// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ9ZpNASYU55LAedGjGWOjUaG8-eFcH-0',
    appId: '1:1014813651932:android:66c50b6710c94dfb2d1519',
    messagingSenderId: '1014813651932',
    projectId: 'whatsapp-backend-dad3c',
    storageBucket: 'whatsapp-backend-dad3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZeLc502mHkmznpzxotwimzHKk1cbBP0g',
    appId: '1:1014813651932:ios:782bd98ee75f95b12d1519',
    messagingSenderId: '1014813651932',
    projectId: 'whatsapp-backend-dad3c',
    storageBucket: 'whatsapp-backend-dad3c.firebasestorage.app',
    iosBundleId: 'com.example.whatsappFixed',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAznA-BxMqbtwasM7lS6XKpEfrt4ghhHUE',
    appId: '1:1014813651932:web:fb43264d9cdf90202d1519',
    messagingSenderId: '1014813651932',
    projectId: 'whatsapp-backend-dad3c',
    authDomain: 'whatsapp-backend-dad3c.firebaseapp.com',
    storageBucket: 'whatsapp-backend-dad3c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAznA-BxMqbtwasM7lS6XKpEfrt4ghhHUE',
    appId: '1:1014813651932:web:7e0af05548e88b5f2d1519',
    messagingSenderId: '1014813651932',
    projectId: 'whatsapp-backend-dad3c',
    authDomain: 'whatsapp-backend-dad3c.firebaseapp.com',
    storageBucket: 'whatsapp-backend-dad3c.firebasestorage.app',
  );

}